const CITIES=['Fort Sterling','Lymhurst','Bridgewatch','Martlock','Thetford','Caerleon','Brecilien'];
const CITY_BONUS={
'Fort Sterling':{base:18,special:['Hammer','Spear','Holy Staff','Plate Helmet','Cloth Armor']},
'Lymhurst':{base:18,special:['Sword','Bow','Arcane Staff','Leather Helmet','Leather Shoes']},
'Bridgewatch':{base:18,special:['Crossbow','Dagger','Cursed Staff','Plate Armor','Cloth Shoes']},
'Martlock':{base:18,special:['Axe','Quarterstaff','Frost Staff','Plate Shoes','Off-Hand']},
'Thetford':{base:18,special:['Mace','Nature Staff','Fire Staff','Leather Armor','Cloth Helmet']},
'Caerleon':{base:18,special:['Gathering Gear','Tool','Food','War Gloves','Shapeshifter Staff']},
'Brecilien':{base:18,special:['Cape','Bag','Potion']}};
const API='https://europe.albion-online-data.com/api/v2/stats/prices/';
let recipes=[],items={},prices=new Map(),loading=false,progress={done:0,total:0},lastPrice=0;
const $=id=>document.getElementById(id);
const fmt=n=>Number.isFinite(Number(n))?Math.round(Number(n)).toLocaleString('pt-PT'):'—';
const pct=n=>Number.isFinite(Number(n))?Number(n).toFixed(1)+'%':'—';
function norm(s){return String(s||'').toLowerCase().replace(/[_-]+/g,' ').replace(/[^a-z0-9áàâãéêíóôõúç .]/gi,'')}
function rrr(p){return 1-1/(1+p/100)}
function production(city,r,focus){const rule=CITY_BONUS[city],name=r.subcategory||r.category||r.name||'';const special=rule.special.some(x=>norm(name).includes(norm(x))||norm(r.name).includes(norm(x)))?15:0;return rule.base+special+(focus?59:0)}
function qprice(item,city,q){const p=prices.get(item);return p?p.get(city+'|'+q)||null:null}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function wanted(){let a=recipes.slice(),q=norm($('search')?.value),cat=$('category')?.value||'',t=$('tier')?.value||'',e=$('enchant')?.value||'';if(q)a=a.filter(r=>norm(r.name).includes(q)||norm(r.uniqueName).includes(q));if(cat)a=a.filter(r=>r.category===cat);if(t)a=a.filter(r=>String(r.tier)===t);if(e)a=a.filter(r=>String(r.enchantment)===e);return a}
function cacheKey(){return 'vgcraft-prices-v2-'+$('quality').value}
function saveCache(){try{const o={timestamp:Date.now(),prices:{}};for(const [id,m] of prices)o.prices[id]=Object.fromEntries(m);localStorage.setItem(cacheKey(),JSON.stringify(o))}catch(e){}}
function loadCache(){try{const o=JSON.parse(localStorage.getItem(cacheKey())||'null');if(!o||Date.now()-o.timestamp>600000)return;for(const [id,v] of Object.entries(o.prices||{}))prices.set(id,new Map(Object.entries(v)));lastPrice=o.timestamp}catch(e){}}
function fillFilters(){const cats=[...new Set(recipes.map(r=>r.category).filter(Boolean))].sort();if($('category'))$('category').innerHTML='<option value="">Todas</option>'+cats.map(x=>`<option>${esc(x)}</option>`).join('')}
async function loadData(){try{recipes=await fetch('data/recipes.json',{cache:'no-store'}).then(r=>r.json());items=await fetch('data/items.json',{cache:'no-store'}).then(r=>r.json());fillFilters();$('status').textContent=`${recipes.length.toLocaleString('pt-PT')} receitas carregadas. A preparar preços...`;loadCache();render();refreshPrices()}catch(e){console.error(e);$('status').textContent='Erro ao carregar recipes.json/items.json.'}}
function idsNeeded(list){const s=new Set();for(const r of list){if(r.uniqueName)s.add(r.uniqueName);for(const m of r.ingredients||[])if(m.uniqueName)s.add(m.uniqueName)}return [...s]}
async function getBatch(batch,q){const url=API+batch.map(encodeURIComponent).join(',')+'.json?locations='+CITIES.map(encodeURIComponent).join(',')+'&qualities='+q;try{const data=await fetch(url).then(r=>r.json());for(const x of data){if(!x.item_id||!x.city)continue;if(!prices.has(x.item_id))prices.set(x.item_id,new Map());prices.get(x.item_id).set(x.city+'|'+x.quality,{sell:Number(x.sell_price_min)||0,sellDate:x.sell_price_min_date,buy:Number(x.buy_price_max)||0,buyDate:x.buy_price_max_date});if(x.sell_price_min_date)lastPrice=Math.max(lastPrice,new Date(x.sell_price_min_date).getTime())}}catch(e){console.warn('Preço:',e)}}
async function refreshPrices(){const ids=idsNeeded(wanted());if(!ids.length){render();return}loading=true;progress={done:0,total:ids.length};render();const q=+$('quality').value,batches=[];for(let i=0;i<ids.length;i+=20)batches.push(ids.slice(i,i+20));let cursor=0;async function worker(){while(true){const i=cursor++;if(i>=batches.length)return;await getBatch(batches[i],q);progress.done=Math.min(progress.done+batches[i].length,ids.length);$('status').textContent=`Preços: ${progress.done.toLocaleString('pt-PT')}/${ids.length.toLocaleString('pt-PT')} itens consultados...`;render()}}await Promise.all(Array.from({length:Math.min(6,batches.length)},worker));loading=false;saveCache();$('status').textContent=`Preços actualizados. ${ids.length.toLocaleString('pt-PT')} itens analisados.`;if($('updated'))$('updated').textContent=lastPrice?new Date(lastPrice).toLocaleString('pt-PT'):'—';render()}
function calc(r){const q=+$('quality').value,focus=$('focus').value==='focus',tax=(+$('tax').value||0)/100,station=(+$('station').value||0)/100;let best=null;for(const craftCity of CITIES){const prod=production(craftCity,r,focus),rate=rrr(prod);let raw=0,missing=false;for(const m of r.ingredients||[]){const p=qprice(m.uniqueName,craftCity,q)||qprice(m.uniqueName,'Caerleon',q);if(!p?.sell){missing=true;break}raw+=m.count*p.sell*(1-rate)}if(missing)continue;const fee=(r.craftingSilver||0)+raw*station,sales=CITIES.map(city=>{const p=qprice(r.uniqueName,city,q);return p?.sell?{city,price:p.sell,date:p.sellDate}:null}).filter(Boolean);if(!sales.length)continue;const sale=sales.sort((a,b)=>b.price-a.price)[0],net=sale.price*(1-tax),profit=net-fee,c={craftCity,saleCity:sale.city,sale:sale.price,cost:fee,profit,roi:fee?profit/fee*100:0,margin:net?profit/net*100:0,rrr:rate*100,prod,saleDate:sale.date};if(!best||c.profit>best.profit)best=c}return best}
function render(){const all=wanted(),a=all.map(r=>({r,c:calc(r)})),sort=$('sort')?.value||'profit';a.sort((x,y)=>sort==='name'?String(x.r.name||x.r.uniqueName).localeCompare(String(y.r.name||y.r.uniqueName)):(Number(y.c?.[sort])||-Infinity)-(Number(x.c?.[sort])||-Infinity));const priced=a.filter(x=>x.c);if($('count'))$('count').textContent=all.length.toLocaleString('pt-PT');if($('priced'))$('priced').textContent=priced.length.toLocaleString('pt-PT');if($('best'))$('best').textContent=priced[0]?fmt(priced[0].c.profit):'—';if($('resultInfo'))$('resultInfo').textContent=loading?`${priced.length} oportunidades calculadas • ${progress.done}/${progress.total} preços carregados`:`${priced.length} oportunidades com preço disponível`;if(!$('rows'))return;$('rows').innerHTML=a.slice(0,100).map(x=>{const r=x.r,c=x.c;if(!c)return `<tr><td><span class="item">${esc(r.name||r.uniqueName)}</span><span class="sub">${esc(r.uniqueName)}</span></td><td>T${r.tier||'?'}${r.enchantment?'.'+r.enchantment:'.0'}</td><td colspan="6"><span class="price-loading">⏳ A consultar preços...</span></td><td><button class="open" data-id="${esc(r.uniqueName)}">Ver</button></td></tr>`;return `<tr><td><span class="item">${esc(r.name||r.uniqueName)}</span><span class="sub">${esc(r.uniqueName)}</span></td><td>T${r.tier||'?'}${r.enchantment?'.'+r.enchantment:'.0'}</td><td>${esc(c.craftCity)}</td><td>${esc(c.saleCity)}<span class="sub">${fmt(c.sale)} / un.</span></td><td class="num">${fmt(c.cost)}</td><td class="profit">${fmt(c.profit)}</td><td>${pct(c.roi)}</td><td>${pct(c.rrr)}</td><td><button class="open" data-id="${esc(r.uniqueName)}">Ver</button></td></tr>`}).join('')||'<tr><td colspan="9" class="empty">Sem receitas para os filtros.</td></tr>';$('rows').querySelectorAll('.open').forEach(b=>b.onclick=()=>showDetail(b.dataset.id))}
function showDetail(id){const r=recipes.find(x=>x.uniqueName===id);if(!r)return;const c=calc(r),q=+$('quality').value;$('details').innerHTML=`<div class="panel-head"><div><span class="kicker">RECEITA</span><h2>${esc(r.name||r.uniqueName)}</h2><span class="badge">${esc(r.uniqueName)}</span></div><span>${c?`Melhor: ${esc(c.craftCity)} → ${esc(c.saleCity)}`:'⏳ A aguardar preços'}</span></div><div class="detail-grid"><div class="box"><h3>MATERIAIS NECESSÁRIOS</h3>${(r.ingredients||[]).map(m=>{const name=items[m.uniqueName]?.name||m.uniqueName;const ps=CITIES.map(city=>{const p=qprice(m.uniqueName,city,q);return p?.sell?{city,price:p.sell}:null}).filter(Boolean).sort((a,b)=>a.price-b.price)[0];return `<div class="material"><span>${esc(name)}<span class="sub">${esc(m.uniqueName)}</span></span><b>${fmt(m.count)}<span class="sub">${ps?fmt(ps.price)+' • '+esc(ps.city):'⏳ preço'}</span></b></div>`}).join('')}</div><div class="box"><h3>MELHOR CRAFT</h3>${c?`<div class="city"><span>Cidade</span><b>${esc(c.craftCity)}</b></div><div class="city"><span>RRR</span><b>${pct(c.rrr)}</b></div><div class="city"><span>Produção</span><b>${c.prod}%</b></div><div class="city"><span>Custo efectivo</span><b>${fmt(c.cost)}</b></div>`:'<p class="empty">Ainda faltam preços.</p>'}</div><div class="box"><h3>MELHOR VENDA</h3>${c?`<div class="city"><span>Cidade</span><b>${esc(c.saleCity)}</b></div><div class="city"><span>Venda</span><b>${fmt(c.sale)}</b></div><div class="city"><span>Lucro líquido</span><b class="profit">${fmt(c.profit)}</b></div><div class="city"><span>ROI</span><b>${pct(c.roi)}</b></div>`:'<p class="empty">Sem preço de venda.</p>'}</div></div>`}
if($('refresh'))$('refresh').onclick=()=>{prices.clear();localStorage.removeItem(cacheKey());refreshPrices()};
['search','category','tier','enchant','focus','tax','station','sort'].forEach(id=>$(id)?.addEventListener('input',render));
$('quality')?.addEventListener('change',()=>{prices.clear();loadCache();render();refreshPrices()});
loadData();
