import fs from 'node:fs/promises';
import path from 'node:path';
const root=process.cwd(), source='https://raw.githubusercontent.com/ao-data/ao-bin-dumps/master/formatted/items.json';
const attr=(o,...ks)=>{if(!o||typeof o!=='object')return;for(const k of ks){if(k in o)return o[k];if(`@${k}` in o)return o[`@${k}`]}};
const arr=v=>Array.isArray(v)?v:(v==null?[]:[v]); const str=v=>v==null?'':String(v);
const id=o=>str(attr(o,'uniqueName','UniqueName','uniquename','id','Id','index','Index'));
const name=o=>{const v=attr(o,'localizedNames','LocalizedNames','name','Name','displayName','DisplayName');if(typeof v==='string')return v;if(v&&typeof v==='object')return v['EN-US']||v['en-US']||v.EN||Object.values(v)[0]||'';return ''};
const req=o=>attr(o,'craftingRequirements','CraftingRequirements','craftingrequirements');
const mats=r=>{if(!r)return[];const x=attr(r,'craftResource','craftresource','craftResourceList','CraftResourceList','resources','Resources');return arr(x).map(m=>({uniqueName:str(attr(m,'uniqueName','UniqueName','uniquename','itemName','itemname','id','Id')),count:Number(attr(m,'count','Count','amount','Amount','itemAmount','itemamount')||0)})).filter(m=>m.uniqueName&&m.count>0)};
const tier=(o,x)=>Number(attr(o,'tier','Tier')||(x.match(/^T([1-8])(?:_|$)/i)||[])[1]||0)||null;
function walk(v,out=[]){if(Array.isArray(v)){v.forEach(x=>walk(x,out));return out}if(!v||typeof v!=='object')return out;if(id(v))out.push(v);for(const[k,x]of Object.entries(v)){const q=k.toLowerCase();if(q==='craftingrequirements'||q==='enchantments')continue;walk(x,out)}return out}
function add(out,seen,item,uid,r,level){const ingredients=mats(r);if(!ingredients.length||seen.has(uid))return;seen.add(uid);out.push({uniqueName:uid,baseUniqueName:id(item),name:name(item),category:str(attr(item,'shopCategory','ShopCategory','category','Category')),subcategory:str(attr(item,'shopSubCategory','ShopSubCategory','shopSubcategory','ShopSubcategory','subcategory','Subcategory')),tier:tier(item,uid),enchantment:level,outputCount:Number(attr(item,'craftingOutputCount','CraftingOutputCount','outputCount','OutputCount')||1)||1,ingredients,craftingSilver:Number(attr(r,'silver','Silver')||0),craftingFocus:Number(attr(r,'craftingFocus','CraftingFocus','craftingfocus')||0),craftingTime:Number(attr(r,'time','Time')||0),source:'ao-bin-dumps',validated:true})}
const res=await fetch(source);if(!res.ok)throw new Error(`HTTP ${res.status}`);const raw=await res.json(),nodes=walk(raw),items={},recipes=[],seen=new Set();
for(const it of nodes){const base=id(it);if(!base)continue;items[base]={name:name(it),category:str(attr(it,'shopCategory','ShopCategory','category','Category')),subcategory:str(attr(it,'shopSubCategory','ShopSubCategory','shopSubcategory','ShopSubcategory','subcategory','Subcategory')),tier:tier(it,base)};add(recipes,seen,it,base,req(it),0);const ens=attr(it,'enchantments','Enchantments'),list=ens?attr(ens,'enchantment','Enchantment'):undefined;for(const e of arr(list)){const lv=Number(attr(e,'enchantmentLevel','EnchantmentLevel','enchantmentlevel','level','Level')||0);add(recipes,seen,it,`${base}_LEVEL${lv}`,req(e)||e,lv)}}
recipes.sort((a,b)=>a.uniqueName.localeCompare(b.uniqueName));await fs.writeFile(path.join(root,'data/items.json'),JSON.stringify(items,null,2));await fs.writeFile(path.join(root,'data/recipes.json'),JSON.stringify(recipes,null,2));await fs.writeFile(path.join(root,'data/sync-report.json'),JSON.stringify({itemNodes:nodes.length,uniqueItems:Object.keys(items).length,recipes:recipes.length,enchantedRecipes:recipes.filter(x=>x.enchantment).length,generatedAt:new Date().toISOString()},null,2));console.log({items:Object.keys(items).length,recipes:recipes.length,enchanted:recipes.filter(x=>x.enchantment).length});
